NLECA Core Newsletter App/Models/Newsletter/ArticleImageInArticleModel.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace NLECA_Core_Newsletter_App.Models.Newsletter
{
    public class ArticleImageInArticleModel
    {
        public int ArticleId { get; private set; }
        public string ArticleTitle { get; set; }
        public int NewsletterId { get; set; }
        public string NewsletterDisplayDate { get; set; }
        public string NewsletterMemo { get; set; }
        public string UploadedByUserId { get; set; }
        public string UploadedByUserName { get; set; }
        public bool IsCurrent { get; set; }
        public string ImageName { get; private set; }
        public string ImageLocation { get; private set; }

        public ArticleImageInArticleModel(DataRow dataRow)
        {
            ArticleId = Int32.Parse(dataRow["ArticleId"].ToString());
            ArticleTitle = dataRow["ArticleTitle"].ToString();
            NewsletterId = Int32.Parse(dataRow["NewsletterId"].ToString());
            NewsletterDisplayDate = dataRow["DisplayDate"].ToString();
            NewsletterMemo = dataRow["Memo"].ToString();
            UploadedByUserId = dataRow["UploadedByUserId"].ToString();
            UploadedByUserName = dataRow["UploadedByUserName"].ToString();
            IsCurrent = string.Equals(dataRow["IsCurrent"].ToString(), "1") ? true : false;
            ImageName = dataRow["ImageName"].ToString();
            ImageLocation = dataRow["ImageLocation"].ToString();
        }
    }
}

NLECA Core Newsletter App/Models/Newsletter/ArticleImageModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.IO;
using System.Linq;
using System.Text;

namespace NLECA_Core_Newsletter_App.Models.Newsletter
{
    public class ArticleImageModel
    {
        private byte[] FileBytes;

        public IFormFile ImageFile { get; private set; }
        public string UploadedByUserId { get; set; }
        public string UploadedByUserName { get; set; }

        public string SimpleCheckSum { get; private set; }
        public string ImageFileExtension { get; private set; }
        public string ImageName { get; private set; }
        public string ImageLocation { get; private set; }
        public bool IsValidImageFormat { get; private set; }

        public ArticleImageModel(Uri storageUri, IFormFile imageFile)
        {
            ImageFile = imageFile;
            FileBytes = ConvertFileToByteArray(imageFile);
            SimpleCheckSum = GetSimpleCheckSumFromFile();
            ImageFileExtension = "." + imageFile.FileName.Split('.')[imageFile.FileName.Split('.').Length - 1];
            ImageName = imageFile.FileName.Remove(imageFile.FileName.IndexOf(ImageFileExtension));
            ImageLocation = string.Format("{0}/{1}", storageUri, imageFile.FileName);
            IsValidImageFormat = GetImageFormat(FileBytes) != ImageFormat.unknown;
        }

        private string GetSimpleCheckSumFromFile()
        {
            byte[] fileBytes = this.FileBytes;

            string simpleCheckSum = GetImageByteArraySimpleCheckSum(fileBytes);

            return simpleCheckSum;
        }

        private enum ImageFormat
        {
            jpeg,
            png,
            gif,
            bmp,
            tiff,
            unknown
        }

        private byte[] ConvertFileToByteArray(IFormFile file)
        {
            byte[] fileBytes;

            using (var memoryStream = new MemoryStream())
            {
                file.CopyTo(memoryStream);
                fileBytes = memoryStream.ToArray();
                return fileBytes;
            }
        }

        private static ImageFormat GetImageFormat(byte[] bytes)
        {
            var jpeg = new byte[] { 255, 216, 255, 224 };   // jpeg
            var jpeg2 = new byte[] { 255, 216, 255, 225 };  // jpeg canon
            var png = new byte[] { 137, 80, 78, 71 };       // PNG
            var gif = Encoding.ASCII.GetBytes("GIF");       // GIF
            var bmp = Encoding.ASCII.GetBytes("BM");        // BMP
            var tiff = new byte[] { 73, 73, 42 };           // TIFF
            var tiff2 = new byte[] { 77, 77, 42 };          // TIFF

            if (jpeg.SequenceEqual(bytes.Take(jpeg.Length)))
                return ImageFormat.jpeg;

            if (jpeg2.SequenceEqual(bytes.Take(jpeg2.Length)))
                return ImageFormat.jpeg;

            if (png.SequenceEqual(bytes.Take(png.Length)))
                return ImageFormat.png;

            if (gif.SequenceEqual(bytes.Take(gif.Length)))
                return ImageFormat.gif;

            if (bmp.SequenceEqual(bytes.Take(bmp.Length)))
                return ImageFormat.bmp;

            if (tiff.SequenceEqual(bytes.Take(tiff.Length)))
                return ImageFormat.tiff;

            if (tiff2.SequenceEqual(bytes.Take(tiff2.Length)))
                return ImageFormat.tiff;

            return ImageFormat.unknown;
        }

        // DO NOT USE FOR HASHING ANYTHING IMPORTANT. THIS IS ONLY FOR CHECKSUMS!!
        public string GetImageByteArraySimpleCheckSum(byte[] imageByteArray)
        {
            string hash = string.Empty;
            int[] hashInts = new int[30];
            int index = 0;
            int lastRemainder = 0;
            foreach (byte imagebyte in imageByteArray)
            {
                int dividend = imagebyte / 7;
                int remainder = imagebyte % 7;
                hashInts[index] = hashInts[index] + lastRemainder + dividend;
                lastRemainder = remainder;
                index++;
                if (index == 30)
                {
                    index = 0;
                }
            }

            for (int i = 0; i < hashInts.Length; i++)
            {
                int preAsciiConversionDigit = hashInts[i] % 62;
                int asciiCharDigit;
                if (preAsciiConversionDigit < 10)
                {
                    asciiCharDigit = preAsciiConversionDigit + 48;
                }
                else if (preAsciiConversionDigit < 36)
                {
                    asciiCharDigit = preAsciiConversionDigit + 55;
                }
                else
                {
                    asciiCharDigit = preAsciiConversionDigit + 61;
                }

                char charToAddToHash = (char)asciiCharDigit;

                hash += charToAddToHash;
            }

            return hash;
        }
    }
}

NLECA Core Newsletter App/Models/Newsletter/EditArticleModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using NLECA_Core_Newsletter_App.Data;
using System;
using System.Collections.Generic;
using System.Linq;

namespace NLECA_Core_Newsletter_App.Models.Newsletter
{
    public class EditArticleModel
    {
        public ArticleModel Article { get; set; }
        public IEnumerable<NewsletterArticleType> ArticleTypes { get; set; }

        public EditArticleModel(ArticleModel article)
        {
            Article = article;
            ArticleTypes = NewsletterArticleType.GetArticleTypes();
        }
    }
}

NLECA Core Newsletter App/Models/Newsletter/Newsletter.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NLECA_Core_Newsletter_App.Models.Newsletter
{
    public class Newsletter
    {
        public int NewsletterId { get; set; }
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public string Memo { get; set; }
        public DateTime PublishedDate { get; set; }
        public bool IsCurrent { get; set; }

        public IEnumerable<Article> Articles { get; set; }

        public Newsletter()
        {
            Articles = new List<Article>();
        }
    }
}

NLECA Core Newsletter App/Controllers/NewsletterController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using NLECA_Core_Newsletter_App.Models.Newsletter;
using NLECA_Core_Newsletter_App.Service.Interfaces;
using Serilog.Core;
using System;
using System.Collections.Generic;
using System.IO;
using System.Security.Claims;

namespace NLECA_Core_Newsletter_App.Controllers
{
    public class NewsletterController : Controller
    {
        private readonly ILogger<NewsletterController> _logger;
        private readonly IConfiguration _config;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly INewsletterService _newsletter;
        private readonly IArticleService _articleService;

        public NewsletterController(ILogger<NewsletterController> logger, IConfiguration config, IHttpContextAccessor httpContextAccessor, INewsletterService newsletter, IArticleService articleService)
        {
            _logger = logger;
            _config = config;
            _httpContextAccessor = httpContextAccessor;
            _newsletter = newsletter;
            _articleService = articleService;
        }


        [Authorize(Roles = "SuperAdmin,Admin,ReadOnlyUser")]
        public IActionResult Index()
        {
            return RedirectToAction("NewsletterManager");
        }

        [Authorize(Roles = "SuperAdmin,Admin,ReadOnlyUser")]
        public IActionResult NewsletterManager()
        {
            List<NewsletterModel> model = _newsletter.GetAllNewsletters();
            return View(model);
        }

        [Authorize(Roles = "SuperAdmin,Admin")]
        public IActionResult AddNewsletter()
        {
            int newsletterId = _newsletter.AddNewsletter();

            return RedirectToAction("EditNewsletter", new { newsletterId = newsletterId });
        }


        [Authorize(Roles = "SuperAdmin,Admin,ReadOnlyUser")]
        public IActionResult EditNewsletter(int newsletterId)
        {
            NewsletterModel model = _newsletter.GetNewsletterById(newsletterId);
            model.IsEdit = true;
            return View(model);
        }

        [Authorize(Roles = "SuperAdmin,Admin")]
        public IActionResult UpdateNewsletter(int newsletterId, string oldMemo, string memo, string oldDisplayDate, string displayDate)
        {
            // handle possible nulls.
            oldMemo = string.IsNullOrEmpty(oldMemo) ? "" : oldMemo.Trim();
            memo = string.IsNullOrEmpty(memo) ? "" : memo.Trim();
            oldDisplayDate = string.IsNullOrEmpty(oldDisplayDate) ? "" : oldDisplayDate.Trim();
            displayDate = string.IsNullOrEmpty(displayDate) ? "" : displayDate.Trim();

            bool memoChanged = (oldMemo.Equals(memo) == false);
            bool displayDateChanged = (oldDisplayDate.Equals(displayDate) == false);

            if (memoChanged || displayDateChanged)
            {
                NewsletterModel oldNewsletter = _newsletter.GetNewsletterById(newsletterId);
                if (memoChanged)
                {
                    oldNewsletter.Memo = memo;
                }
                if (displayDateChanged)
                {
                    oldNewsletter.DisplayDate = displayDate;
                }
                bool successfulUpdate = _newsletter.UpdateNewsletter(oldNewsletter);
            }

            return RedirectToAction("EditNewsletter", new { newsletterId = newsletterId });
        }

        [Authorize(Roles = "SuperAdmin,Admin")]
        public IActionResult RemoveNewsletter(int newsletterId)
        {
            if (User.IsInRole("ReadOnlyUser"))
            {
                return RedirectToAction("NewsletterManager");
            }

            try
            {
                _newsletter.DeleteNewsletter(newsletterId);
            }
            catch (Exception ex)
            {
                string error = string.Format("There was an error deleting a newsletter with the id {0}", newsletterId);
                _logger.LogError(error, ex);
            }
                
            return RedirectToAction("NewsletterManager");
        }

        [Authorize(Roles = "SuperAdmin,Admin")]
        [HttpPost]
        public IActionResult SaveNewsletter(NewsletterModel newsletter)
        {
            NewsletterModel model = newsletter;
            return RedirectToAction("NewsletterManager");
        }

        [Authorize(Roles = "SuperAdmin,Admin")]
        public IActionResult UpdateNewsletterDateRange(string start, string end, int newsletterId)
        {
            var startParts = start.Split('-');
            int startYear = Int32.Parse(startParts[0]);
            int startMonth = Int32.Parse(startParts[1]);
            int startDay = Int32.Parse(startParts[2]);

            var endParts = end.Split('-');
            int endYear = Int32.Parse(endParts[0]);
            int endMonth = Int32.Parse(endParts[1]);
            int endDay = Int32.Parse(endParts[2]);

            DateTime startDate = new DateTime(startYear, startMonth, startDay);
            DateTime endDate = new DateTime(endYear, endMonth, endDay);

            NewsletterModel newsletter = _newsletter.GetNewsletterById(newsletterId);
            newsletter.EventsStartDate = startDate;
            newsletter.EventsEndDate = endDate;
            _newsletter.UpdateNewsletter(newsletter);

            return RedirectToAction("NewsletterManager");
        }

        [Authorize(Roles = "SuperAdmin,Admin")]
        public IActionResult PublishNewsletter(int newsletterId)
        {
            _newsletter.PublishNewsletter(newsletterId);
            return RedirectToAction("NewsletterManager");
        }

        [Authorize(Roles = "SuperAdmin,Admin")]
        public IActionResult UnpublishNewsletter(int newsletterId)
        {
            _newsletter.UnpublishNewsletter(newsletterId);
            return RedirectToAction("NewsletterManager");
        }
    }
}

NLECA Core Newsletter App/ViewComponents/AlertsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using NLECA_Core_Newsletter_App.Models.Alert;
using NLECA_Core_Newsletter_App.Service.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;

namespace NLECA_Core_Newsletter_App.ViewComponents
{
    public class AlertsViewComponent : ViewComponent
    {
        private readonly IAlertService _alerts;
        private List<int> hiddenAlerts = new List<int>();

        public AlertsViewComponent(IAlertService alertService)
        {
            _alerts = alertService;
        }
        public IViewComponentResult Invoke()
        {
            if (HttpContext.Request.Cookies["HiddenAlerts"] != null)
            {
                hiddenAlerts = HttpContext.Request.Cookies["HiddenAlerts"].Split('-')
                    .Select(Int32.Parse).ToList();
            }

            IEnumerable<AlertModel> currentAlerts = _alerts.GetAllCurrentAlerts()
                .Where(x => hiddenAlerts.Contains(x.AlertId) == false);
            return View("Default", currentAlerts);
        }
    }
}

NLECA Core Newsletter App/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NLECA_Core_Newsletter_App.Models;

namespace NLECA_Core_Newsletter_App.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            FooterModel footerModel = new FooterModel()
            {
                BrandName = "loiacanoDesigns"
            };

            return View(footerModel);
        }
    }
}

NLECA Core Newsletter App/ViewComponents/HeaderMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NLECA_Core_Newsletter_App.Models;

namespace NLECA_Core_Newsletter_App.ViewComponents
{
    public class HeaderMenuViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            HeaderMenuModel headerMenu = new HeaderMenuModel()
            {
                BrandName = "NLECA"
            };

            return View(headerMenu);
        }
    }
}

NLECA Core Newsletter App/ViewComponents/SpinnerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NLECA_Core_Newsletter_App.Models;

namespace NLECA_Core_Newsletter_App.ViewComponents
{
    public class SpinnerViewComponent : ViewComponent
    {        
        public IViewComponentResult Invoke()
        {
            bool useSpinner = HttpContext.Request.Cookies["UseSpinner"] != null;
            SpinnerModel spinner = new SpinnerModel(useSpinner);

            return View(spinner);
        }
    }
}

NLECA Core Newsletter App/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>NLECA - @ViewData["Title"]</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/jquery-ui/jquery-ui.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    @RenderSection("HeadIncludes", required: false)
</head>
<body>
    <header>
        @await Component.InvokeAsync("HeaderMenu")
    </header>
    <div id="AlertArea">
        @await Component.InvokeAsync("Alerts")
    </div>
    @await Component.InvokeAsync("SplashScreen")
    @await Component.InvokeAsync("Spinner")

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        @await Component.InvokeAsync("Footer")

    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/JSDateHelpers.js" asp-append-version="true"></script>
    <script src="~/js/Alert/DisplayedAlerts.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

NLECA Core Newsletter App/Views/Shared/_Newsletter.cshtml
@using NLECA_Core_Newsletter_App.Models.Newsletter;
@using NLECA_Core_Newsletter_App.Models.Event;

@model NewsletterModel;

@section Scripts {
    <script src="~/js/Article/NewsletterArticle.js"></script>
}

@if (Model.CreatedDate != DateTime.MinValue)
{
    <div class="container">
        <div class="row banner">
            <div class="col-sm-3">
                <img class="d-none d-md-block d-lg-block d-xl-block" src="~/Images/NewsletterImages/newsicon.jpg" />
            </div>
            <div class="col-sm-6 title">
                <h1>NLECA Newsletter</h1>
            </div>
            <div class="col-sm-3 date">
                <h2 class="newsletterDate">@DateTime.Parse(Model.DisplayDate).ToString("MMMM yyyy")</h2>
                @if (Model.IsEdit)
                {
                    <form action="/Newsletter/UpdateNewsletter" method="post">
                        <input type="hidden" name="newsletterId" value="@Model.NewsletterId" />
                        <input type="hidden" name="oldDisplayDate" value="@Model.DisplayDate" />

                        <div id="displayDateEditArea" style="display: none;">
                            <input type="hidden" name="newsletterId" value="@Model.NewsletterId" />
                            <input type="month" id="start" name="displayDate" min="2018-03" value="@Model.DisplayDate">
                            <button type="submit" id="displayDateSaveChanges">Save Changes</button>
                            <button type="button" id="displayDateEditCancel">Cancel</button>
                        </div>
                    </form>
                }
            </div>
        </div>
    </div>


    @if (Model.Articles.Count() == 0)
    {
        <h1>
            This newsletter does not have any articles yet...
            @if (Model.IsEdit)
            {
                <span class="btn btn-primary addArticleButton hoverPointer">Add One</span>
            }
        </h1>
    }
    else
    {
        <div id="TableOfContentsWrapper">
            <div id="TableOfContents">
                <div class="title">
                    <span>Inside this Issue</span>
                </div>
                <div id="sortableTableOfContents" class="articleSorter">
                    @foreach (ArticleModel article in Model.Articles)
                    {
                        <div>
                            <a href="@string.Format("#article{0}", article.ArticleId)">@article.ArticleTableOfContentsText</a>
                        </div>
                    }
                    @if (Model.IsEdit == false)
                    {
                        @if (Model.Events.Count() > 0)
                        {
                            <div>
                                <a href="#upcomingEvents">Upcoming Events</a>
                            </div>
                        }
                        <div>
                            <a href="#boardMemberContacts">Contacts</a>
                        </div>
                    }
                </div>
            </div>
            @if (Model.IsEdit)
            {
                <button class="changeArticleOrderButton" style="margin: 16px auto;">Change Article Order</button>
                <button class="saveArticleOrderButton" style="margin: 16px auto;">Save Article Order</button>
                <div>
                    <button type="button" class="btn btn-primary addArticleButton">Add Article</button>
                </div>

            }
        </div>

        @if (Model.IsEdit)
        {
            <form id="EditArticleForm" action="/Article/EditArticle" method="post">
                <input id="EditArticleFormInput" type="hidden" name="articleId" value="" />
            </form>
        }

        <div id="Articles">
            @foreach (ArticleModel article in Model.Articles)
            {
                <partial name="/Views/Article/Partials/_ArticleInNewsletter.cshtml" model="article" />


            }
        </div>
    }

    <a name="upcomingEvents"></a>

    @if (Model.Events.Count() == 0)
    {
        <div class="eventArea">
            <h2>There are no events for this Newsletter.</h2>
        </div>
    }

    @if (Model.IsEdit)
    {
        <div class="eventDateRangeEditArea">
            <div>
                <label>Start of Event Date Range</label>
                <input id="EventDateRangeStartInput" type="date" value="@Model.EventsStartDate.ToString("yyyy-MM-dd")" />

                <label>End of Event Date Range</label>
                <input id="EventDateRangeEndInput" type="date" value="@Model.EventsEndDate.ToString("yyyy-MM-dd")" />

                <button class="saveEventDateRangeButton"> Update Event Date Range</button>
            </div>
            <div id="ManageEventsRedirectArea">
                <div>
                    <span>OR</span>
                </div>
                <button id="ManageEventsButton">Manage Events</button>
            </div>
        </div>
    }

    @if (Model.Events.Count() != 0)
    {
        <div class="eventArea">
            <partial name="/Views/Event/Partials/_EventsInNewsletter.cshtml" model="Model.Events" />
        </div>
    }

    <a name="boardMemberContacts"></a>
    <div>
        <h2>Contacts:</h2>
        <span>THIS IS WHERE CONTACTS WILL GO</span>
    </div>
}
else
{
    <h2>There is no published newsletter to display.</h2>
}