NLECA Core Newsletter App/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.WindowsAzure.Storage.Blob;
using NLECA_Core_Newsletter_App.Data;
using NLECA_Core_Newsletter_App.Models.Newsletter;
using NLECA_Core_Newsletter_App.Service.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;

namespace NLECA_Core_Newsletter_App.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IArticleService _articleService;
        private readonly IArticleImageService _imageService;
        private readonly IAzureStorageService _azureStorageService;
        private readonly UserManager<ApplicationIdentityUser> _userManager;

        public ArticleController(
            IConfiguration configuration
            , IArticleService articleService
            , IArticleImageService imageService
            , IAzureStorageService azureStorageService
            , UserManager<ApplicationIdentityUser> userManager)
        {
            _configuration = configuration;
            _articleService = articleService;
            _imageService = imageService;
            _azureStorageService = azureStorageService;
            _userManager = userManager;
        }

        [Authorize(Roles = "SuperAdmin,Admin,ReadOnlyUser")]
        public IActionResult Index()
        {
            //No index page so redirect to newsletterManager
            return RedirectToAction("/Newsletter/NewsletterManager");
        }

        [Authorize(Roles = "SuperAdmin,Admin,ReadOnlyUser")]
        public IActionResult AddArticle(int newsletterId)
        {
            int articleId = _articleService.AddArticleToNewsletter(newsletterId);

            return RedirectToAction("EditArticle", new { articleId });
        }

        [Authorize(Roles = "SuperAdmin,Admin,ReadOnlyUser")]
        public IActionResult EditArticle(int articleId)
        {
            ArticleModel article = _articleService.GetArticleByArticleId(articleId);
            EditArticleModel model = new EditArticleModel(article);

            return View(model);
        }


        [Authorize(Roles = "SuperAdmin,Admin")]
        public IActionResult UpdateArticle(ArticleModel article, IFormFile imageFile, string redirect)
        {
            if (imageFile != null)
            {
                CloudBlobContainer container = _azureStorageService.GetBlobContainer(_configuration["AzureStorageConnectionString"], "article-images");
                Uri storageUri = container.StorageUri.PrimaryUri;
                // USE THIS CODE IF THE STORAGE EMULATOR GETS REMADE AND GIVES YOU A HARD TIME
                //var permissions = container.GetPermissionsAsync().Result;
                //permissions.PublicAccess = BlobContainerPublicAccessType.Container;
                //container.SetPermissionsAsync(permissions);
                ArticleImageModel articleImage = new ArticleImageModel(storageUri, imageFile);
                articleImage.UploadedByUserId = _userManager.GetUserId(this.User);
                articleImage.UploadedByUserName = this.User.Identity.Name;
                _imageService.UploadArticleImage(articleImage);

                article.ImageFileLocation = articleImage.ImageLocation;
                _articleService.UpdateArticle(article);
                return RedirectToAction("EditArticle", new { articleId = article.ArticleId });
            }
            _articleService.UpdateArticle(article);

            if (redirect.Equals("ArticleImageManager"))
            {
                return RedirectToAction("ArticleImageManager", "ArticleImage", new { articleId = article.ArticleId });
            }

            return RedirectToAction("EditNewsletter", "Newsletter", new { article.NewsletterId });
        }

        [Authorize(Roles = "SuperAdmin,Admin")]
        public IActionResult UpdateArticleOrder(IEnumerable<string> articleIds, IEnumerable<string> newArticleOrder)
        {
            bool success = true;
            string[] newArticleOrderArray = newArticleOrder.ToArray();
            string[] articleIdsArray = articleIds.ToArray();
            for (int i = 0; i < newArticleOrderArray.Length; i++)
            {
                if (i + 1 != Int32.Parse(newArticleOrderArray[i]))
                {
                    int newArticleSequence = Int32.Parse(newArticleOrderArray[i]);
                    int articleId = Int32.Parse(articleIdsArray[i]);
                    if (!_articleService.UpdateArticleSequence(articleId, i + 1))
                    {
                        success = false;
                    }
                }
            }

            if (success)
            {
                return Json(new { success = true, responseText = "Sequences successfully updated" });
            }
            return Json(new { success = false, responseText = "There was an error updating sequences." });
        }

        [Authorize(Roles = "SuperAdmin,Admin")]
        public IActionResult RemoveArticle(int newsletterId, int articleId)
        {
            _articleService.DeleteArticle(articleId);
            return RedirectToAction("EditNewsletter", "Newsletter", new { newsletterId });
        }
    }
}

NLECA Core Newsletter App/Views/Article/EditArticle.cshtml
@using NLECA_Core_Newsletter_App.Models.Newsletter;

@model EditArticleModel
@{
    ViewData["Title"] = "Article Editor";
}

@section HeadIncludes {
    <link href="~/lib/jquery-ui/themes/smoothness/jquery-ui.css" rel="stylesheet" />
    <link href="~/css/EditArticle.css" rel="stylesheet" />
    <script src="https://cdn.ckeditor.com/4.14.0/standard/ckeditor.js"></script>
}

@section Scripts {
    <script src="~/js/Article/EditArticle.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.js"></script>
}

<h1>Article Editor</h1>

<h2>Added: @Model.Article.DateAdded by UserId: @Model.Article.AddedBy</h2>

<input hidden id="ModelArticleId" value="@Model.Article.ArticleId" />

<form id="ArticleUpdater" asp-controller="Article" asp-action="UpdateArticle" data-ajax="true" data-ajax-method="POST" enctype="multipart/form-data">

    <input hidden asp-for="Article.ArticleId" />
    <input hidden asp-for="Article.NewsletterId" />
    <input hidden asp-for="Article.ArticleSequence" />
    <input hidden asp-for="Article.ImageFileLocation" id="articleImageFileLocation" />
    <input hidden asp-for="Article.AddedBy" />
    <input hidden asp-for="Article.DateAdded" />


    <label for="articleTypeSelector">Article Type: </label>
    <select id="ArticleTypeDropdown"
            asp-for="Article.ArticleType"
            asp-items="@(new SelectList(Model.ArticleTypes, "IntValue", "Text"))">
    </select>

    <div>
        <label for="articleTableOfContentsText">Table of contents Text: </label>
        <input id="ArticleTableOfContentsText" asp-for="Article.ArticleTableOfContentsText" />
    </div>
    <div>
        <label for="articleTitle">Article Title: </label>
        <input id="ArticleTitle" asp-for="Article.ArticleTitle" />
    </div>


    <div class="articleContent">
        <div class="topArticleImage">
            <div class="dragAndDropImageArea">
                @if (string.IsNullOrEmpty(Model.Article.ImageFileLocation))
                {
                    <img class="dragAndDropImage" src="../../Images/ArticleImages/draganddropimage.png" />
                }
                else
                {
                    <img class="dragAndDropImage" src="@Model.Article.ImageFileLocation" />
                }
            </div>
        </div>
        <div class="leftArticleImage">
            <div class="dragAndDropImageArea">
                @if (string.IsNullOrEmpty(Model.Article.ImageFileLocation))
                {
                    <img class="dragAndDropImage" src="../../Images/ArticleImages/draganddropimage.png" />
                }
                else
                {
                    <img class="dragAndDropImage" src="@Model.Article.ImageFileLocation" />
                }
            </div>
        </div>
        <div class="rightArticleImage">
            <div class="dragAndDropImageArea">
                @if (string.IsNullOrEmpty(Model.Article.ImageFileLocation))
                {
                    <img class="dragAndDropImage" src="../../Images/ArticleImages/draganddropimage.png" />
                }
                else
                {
                    <img class="dragAndDropImage" src="@Model.Article.ImageFileLocation" />
                }
            </div>
        </div>

        <textarea id="ArticleText" asp-for="Article.ArticleText"></textarea>

        <div class="bottomArticleImage">
            <div class="dragAndDropImageArea">
                @if (string.IsNullOrEmpty(Model.Article.ImageFileLocation))
                {
                    <img class="dragAndDropImage" src="../../Images/ArticleImages/draganddropimage.png" />
                }
                else
                {
                    <img class="dragAndDropImage" src="@Model.Article.ImageFileLocation" />
                }
            </div>
        </div>
    </div>
    <input hidden type="file" name="imageFile" id="ImageFileInput" accept="image/*" />
    <input hidden name="redirect" id="redirect" value="EditNewsletter" />

    <button type="submit">Save Changes</button>

    <button id="ArticleEditCancelButton" type="button">Cancel</button>
    <button id="ArticleDeleteButton"
            type="button"
            data-newsletterid="@Model.Article.NewsletterId"
            data-articleid="@Model.Article.ArticleId">
        DELETE ARTICLE
    </button>
</form>

@* DIALOGS *@
<div id="DeleteArticleDialog"
     title="DELETE?">
    <span class="dialogTextLine">
        Are you
        <span class="dialogWarningText">ABSOLUTELY SURE</span>
        you would like to
        <span class="dialogWarningText">DELETE</span>
        this article?
    </span>
    <span class="dialogTextLine">
        No data of this article will be saved.
    </span>
    <span class="dialogTextLine">
        It will be gone forever.
    </span>
</div>